### ISSUE TITLE
error when running locally

### ISSUE THREAD

**Issue by jlaceda** [teamlumpia/swft_marketing_home#1]
Warning: Invalid DOM property `for`. Did you mean `htmlFor`?

**Comment by jlaceda** [comment]
full error:
```
Warning: Invalid DOM property `for`. Did you mean `htmlFor`?
    at label
    at div
    at div
    at Col (/home/john/github/swft_marketing_home/node_modules/react-bootstrap/cjs/Col.js:23:23)
    at div
    at Row (/home/john/github/swft_marketing_home/node_modules/react-bootstrap/cjs/Row.js:25:23)
    at form
    at Form (/home/john/github/swft_marketing_home/node_modules/react-bootstrap/cjs/Form.js:41:23)
    at div
    at Col (/home/john/github/swft_marketing_home/node_modules/react-bootstrap/cjs/Col.js:23:23)
    at div
    at Row (/home/john/github/swft_marketing_home/node_modules/react-bootstrap/cjs/Row.js:25:23)
    at div
    at Container (/home/john/github/swft_marketing_home/node_modules/react-bootstrap/cjs/Container.js:24:23)
    at div
    at Login
    at div
    at div
    at Menu
    at main
    at div
    at Home
    at MyApp (webpack-internal:///./pages/_app.js:21:3)
    at AppContainer (/home/john/github/swft_marketing_home/node_modules/next/dist/server/render.js:293:29)
```

**Comment by jlaceda** [comment]
fixed in https://github.com/teamlumpia/swft_marketing_home/commit/51ac96982428996c7df80d88f5f3fd704a24f03a
